name: 'Lint Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: |
        flake8 --version
        find . -name "*.py" -not -path "*/migrations/*" -exec flake8 --max-line-length=104 {} +

  lint_js:
    name: Lint JS Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install jshint
      run: npm install jshint --global

    - name: Run jshint
      run: |
        find . -name "*.js" \
          -not -path "./server/frontend/*" \
          -not -path "./server/djangoenv/*" \
          -not -name "jquery*" \
          -exec jshint --config .jshintrc {} +
